### PR TITLE
Remove exact package restrictions

### PR DESCRIPTION
**Pull request by mernst**
Per https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/, using exact package versions is not a best practice.

### CODE REVIEW

**Comment by Thomsch** [comment]
Mike, did you try to run Flexeme on a fresh virtual environment after these changes? 

These changes should break Flexeme’s implementation because Flexeme uses methods that are deprecated in latter versions of networkx. I don’t remember exactly which method of the top  of my head.

**Comment by mernst** [comment]
Yes, I did try to run Flexeme.  I reported the problem in https://github.com/Thomsch/untangling-tools-benchmark/issues/27 .

I don't see any use in Flexeme of deprecated methods.
I believe that the deprecation problem was due to (in `setup.py`):  'networkx==2.3', 'numpy==1.23.5'.  Unpinning all the versions together does seem to work, though I don't have an end-to-end test as confirmation.  Does an end-to-end test exist in this repository?

**Comment by mernst** [comment]
@Thomsch Could you please review and merge this pull request?

**Comment by Thomsch** [comment]
Thank you for the update. It looks like I missed your reply.

**Comment by Thomsch** [comment]
>  Does an end-to-end test exist in this repository?

Unfortunately, there are no end-to-end tests. One must run the instructions on the README.

It would be great if there is a sample synthetic commit that we can run automatically. I created issue #5 for it.

**Review by Thomsch — CHANGES_REQUESTED** [review]
The updated version of networkx is an issue. When running the synthetic benchmark, the following error arises:

```
[2023-07-14 13:10:16][root] ERROR: 'MultiDiGraph' object has no attribute 'node'
Traceback (most recent call last):
  File "flexeme/tangle_concerns/generate_corpus.py", line 246, in worker
    raise e
  File "flexeme/tangle_concerns/generate_corpus.py", line 239, in worker
    delta_pdg = delta_gen(temp_dir_worker + '/after_pdg.dot',
  File "/Users/thomas/Workplace/Flexeme/flexeme/deltaPDG/deltaPDG.py", line 19, in __call__
    self.deltaPDG = self.merger(before_apdg=marked_before, after_apdg=marked_after)
  File "/Users/thomas/Workplace/Flexeme/flexeme/deltaPDG/Util/merge_marked_pdgs.py", line 24, in __call__
    equivalent = self.eq_utils.node_eq(before_apdg, node, after_apdg, other_node)
  File "/Users/thomas/Workplace/Flexeme/flexeme/deltaPDG/Util/equivalence_util.py", line 16, in node_eq
    if not (self.node_label_eq(graph_a.node[node_a]['label'], graph_b.node[node_b]['label'])):
```

The calls `graph_a.node[node_a]` and `graph_b.node[node_b]` are triggering an exception because `.node` attribute doesn't exists in newer versions of networkx.

The [release notes](https://networkx.org/documentation/stable/release/release_2.4.html#deprecations) recommend to use `.nodes[]` instead.

**Comment by mernst** [comment]
> When running the synthetic benchmark, the following error arises:
> ...

Could you tell me the exact command you ran?
I tried to follow the instructions in README.md, but the third command failed:

```
% python flexeme/tangle_concerns/tangle_by_file.py /tmp/${USER}/commons-lang /tmp/${USER} .

Traceback (most recent call last):
  File "/home/mernst/research/version-control/Flexeme-fork-thomsch-branch-no-python-requirement/flexeme/tangle_concerns/tangle_by_file.py", line 13, in <module>
    from flexeme.deltaPDG.Util.git_util import Git_Util
ModuleNotFoundError: No module named 'flexeme'
% pwd
/home/mernst/research/version-control/Flexeme-fork-thomsch-branch-no-python-requirement
``

**Comment by Thomsch** [comment]
I'll get back to you after the ICSE deadline on this.

**Comment by mernst** [comment]
Can this be merged now?  This branch is being used under CI, which is passing.

**Comment by Thomsch** [comment]
Not it cannot be merged. See my reply on https://github.com/Thomsch/Flexeme/pull/1#pullrequestreview-1530983964

**Comment by mernst** [comment]
@Thomsch I changed `G.node` to `G.nodes`.  Could you check whether this works for you now?  Thanks.

**Comment by Thomsch** [comment]
> @Thomsch I changed `G.node` to `G.nodes`. Could you check whether this works for you now? Thanks.

Will do! Thank you for resurfacing this PR.

**Comment by Thomsch** [comment]
Updating `networkx` to the latest version creates the following error:

```
[2023-09-05 13:56:14][root] ERROR: Error while processing synthetic commit 7ee33f6ef446fcdd4b49af6cab6890afdbbcd5cd_6cf70f3117fbf560c34f516f63d842751aab1e91:
[2023-09-05 13:56:14][root] ERROR: Node names and attributes should not contain ":" unless they are quoted with "".                For example the string 'attribute:data1' should be written as '"attribute:data1"'.                Please refer https://github.com/pydot/pydot/issues/258
```

This is probably due because Flexeme stores group labels in the nodes attributes as "<group_number>:<AST label>".

**Review by Thomsch — APPROVED** [review]

**Comment by Thomsch** [comment]
These last changes fix the error caused by `:` in the node attributes. `:` would also be present when the node represents a ternary attribute. 

I fixed this bug by quoting the node label attribute when the dot file is written on disk.

**Pull request merged**
